jobs:
  - job: Setup
    strategy:
      matrix:
        Server:
          demands: mad_server
        Client:
          demands: mad_client
    pool:
      name: MLNX
      demands: $(demands)
    workspace:
      clean: outputs
    steps:
      - checkout: self
        clean: true
        fetchDepth: 100
        retryCountOnTaskFailure: 5
      - bash: |
          source ./contrib/test_mad.sh
          setup
          build_ucx
        displayName: Setup

  - job: ServerUp
    dependsOn: Setup
    displayName: Server Up
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          run_mad_server
        displayName: Server Up

      - task: Bash@3
        name: Set_Vars
        inputs:
          targetType: "inline"
          script: |
            source ./contrib/test_mad.sh
            set_vars
        displayName: Set Vars

  - job: TestLid
    dependsOn: ServerUp
    displayName: Test Lid
    timeoutInMinutes: 10
    pool:
      name: MLNX
      demands: mad_client
    variables:
      LID: $[ dependencies.ServerUp.outputs['Set_Vars.LID'] ]
    steps:
      - checkout: none
      - bash: $(Build.SourcesDirectory)/install/bin/ucx_perftest -t tag_bw -e -K "$(HCA)" -e lid:"$(LID)"
        displayName: Test LID

  - job: ServerRestart
    dependsOn: TestLid
    displayName: Server Restart
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          srv_stop
          srv_start
        displayName: Server Restart

  - job: TestGuid
    dependsOn:
      - ServerUp
      - ServerRestart
    displayName: Test Guid
    timeoutInMinutes: 10
    pool:
      name: MLNX
      demands: mad_client
    variables:
      GUID: $[ dependencies.ServerUp.outputs['Set_Vars.GUID'] ]
    steps:
      - checkout: none
      - bash: $(Build.SourcesDirectory)/install/bin/ucx_perftest -t tag_bw -e -K "$(HCA)" -e guid:"$(GUID)"
        displayName: Test GUID

  - job: ServerStop
    dependsOn: TestGuid
    displayName: Server Stop
    condition: always()
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          srv_stop
        displayName: Server Stop
