jobs:
  - job: SetupServer
    displayName: Setup Server
    pool:
      name: MLNX
      demands: mad_server
    workspace:
      clean: outputs
    steps:
      - checkout: self
        clean: true
        fetchDepth: 100
        retryCountOnTaskFailure: 5
      - bash: |
          source ./contrib/test_mad.sh
          setup
          build_ucx
        displayName: Setup Server

  - job: SetupClient
    displayName: Setup Client
    pool:
      name: MLNX
      demands: mad_client
    workspace:
      clean: outputs
    steps:
      - checkout: self
        clean: true
        fetchDepth: 100
        retryCountOnTaskFailure: 5
      - bash: |
          source ./contrib/test_mad.sh
          setup
          build_ucx
        displayName: Setup Client

  - job: ServerUp
    dependsOn: SetupServer
    displayName: Server Up
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          run_mad_server
        displayName: Server Up

      - task: Bash@3
        name: Set_Vars
        inputs:
          targetType: "inline"
          script: |
            source ./contrib/test_mad.sh
            set_vars
        displayName: Set Vars

  - job: TestLid
    dependsOn:
      - ServerUp
      - SetupClient
    displayName: Test Lid
    timeoutInMinutes: 10
    pool:
      name: MLNX
      demands: mad_client
    variables:
      LID: $[ dependencies.ServerUp.outputs['Set_Vars.LID'] ]
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          run_mad_test_lid
        env:
          LID: $(LID)
        displayName: Test LID

  - job: ServerRestart
    dependsOn: TestLid
    displayName: Server Restart
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          srv_stop
          srv_start
        displayName: Server Restart

  - job: TestGuid
    dependsOn:
      - ServerUp
      - ServerRestart
    displayName: Test Guid
    timeoutInMinutes: 10
    pool:
      name: MLNX
      demands: mad_client
    variables:
      GUID: $[ dependencies.ServerUp.outputs['Set_Vars.GUID'] ]
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          run_mad_test_guid
        env:
          GUID: $(GUID)
        displayName: Test GUID

  - job: ServerStop
    dependsOn: TestGuid
    displayName: Server Stop
    condition: always()
    pool:
      name: MLNX
      demands: mad_server
    steps:
      - checkout: none
      - bash: |
          source ./contrib/test_mad.sh
          srv_stop
        displayName: Server Stop
