parameters:
  worker_ids: [0, 1, 2, 3]
  num_workers: 4
  demands: []
  name: subtest
  container:
  run_tests: yes
  proto_enable: yes
  asan_check: no
  valgrind_check: no

jobs:
  - job: tests_${{ parameters.name }}
    pool:
      name: MLNX
      demands: ${{ parameters.demands }}
    displayName: ${{ parameters.name }} on worker
    timeoutInMinutes: 360
    strategy:
      matrix:
        ${{ each wid in parameters.worker_ids }}:
          ${{ wid }}:
            worker_id: ${{ wid }}
    ${{ if parameters.container }}:
      container: ${{ parameters.container }}
    workspace:
      clean: outputs
    steps:
      - checkout: self
        clean: true
        fetchDepth: 100
        retryCountOnTaskFailure: 5

      - bash: |
          source ./buildlib/az-helpers.sh
          check_gpu ${{ parameters.name }}
          az_init_modules
          ./contrib/test_jenkins.sh
          exit $?
        displayName: Run ./contrib/test_jenkins.sh
        env:
          nworkers: ${{ parameters.num_workers }}
          worker: $(worker_id)
          BUILD_NUMBER: "$(Build.BuildId)-$(Build.BuildNumber)"
          JOB_URL: "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          # $AZP_AGENT_ID is set for every self-hosted Azure agent (uniq for one host, from 1 to N)
          EXECUTOR_NUMBER: $(AZP_AGENT_ID)
          RUN_TESTS: ${{ parameters.run_tests }}
          TEST_PERF: ${{ parameters.test_perf }}
          PROTO_ENABLE: ${{ parameters.proto_enable }}
          ASAN_CHECK: ${{ parameters.asan_check }}
          VALGRIND_CHECK: ${{ parameters.valgrind_check }}
          RUNNING_IN_AZURE: yes
