parameters:
  container: ucxx_rapidsai_ci_conda
  slices: []

jobs:
  - ${{ each slice in parameters.slices }}:
    - job: ucxx_conda_cpp_build_${{ slice.name }}
      workspace:
        clean: all
      pool:
        name: MLNX
        demands: ${{ slice.demands }}
      displayName: 'UCXX conda-cpp-build (${{ slice.name }})'
      container: ${{ parameters.container }}
      timeoutInMinutes: 60
      variables:
        UCX_DIR: $(Agent.BuildDirectory)/ucx
        UCXX_DIR: $(Agent.BuildDirectory)/ucxx
        RAPIDS_CUDA_VERSION: ${{ slice.rapids_cuda_version }}
        RAPIDS_PY_VERSION: ${{ slice.rapids_py_version }}
        RAPIDS_BLD_OUTPUT_DIR: $(Build.ArtifactStagingDirectory)

      steps:
        - checkout: self
          path: ucx
          fetchDepth: 100
          retryCountOnTaskFailure: 5

        - checkout: ucxx
          path: ucxx
          retryCountOnTaskFailure: 5

        - bash: bash $(UCX_DIR)/buildlib/tools/build_ucxx.sh conda_cpp
          displayName: Build UCXX conda C++ package

        - task: PublishBuildArtifacts@1
          displayName: Publish conda-cpp artifact
          inputs:
            pathToPublish: $(RAPIDS_BLD_OUTPUT_DIR)
            artifactName: ucxx-conda-cpp-${{ slice.name }}
