#!/bin/sh
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2014.  ALL RIGHTS RESERVED.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance using specific CPU.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/configure-release \
	--with-avx \
	--with-sse41 \
	"$@"
