#!/bin/sh
#
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2001-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# Copyright (C) UT-Battelle, LLC. 2014. ALL RIGHTS RESERVED.
# SPDX-License-Identifier: BSD-3-Clause
# See file LICENSE for terms.
#

#
# UCX build for development.
# Full logging and an runtime checks.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../configure \
	--enable-gtest \
	--enable-examples \
	--with-valgrind \
	--enable-profiling \
	--enable-frame-pointer \
	--enable-stats \
	--enable-debug-data \
	--enable-mt \
	"$@"
