#!/bin/sh
#
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2001-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance, use non-portable CPU optimizations.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/configure-release \
	--enable-optimizations \
	"$@"
