/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucp_UcpContext */

#ifndef _Included_org_ucx_jucx_ucp_UcpContext
#define _Included_org_ucx_jucx_ucp_UcpContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucp_UcpContext
 * Method:    createContextNative
 * Signature: (Lorg/ucx/jucx/ucp/UcpParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_ucx_jucx_ucp_UcpContext_createContextNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_ucx_jucx_ucp_UcpContext
 * Method:    cleanupContextNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpContext_cleanupContextNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
