/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_Bridge */

#ifndef _Included_org_ucx_jucx_Bridge
#define _Included_org_ucx_jucx_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_Bridge
 * Method:    createContextNative
 * Signature: (Lorg/ucx/jucx/ucp/UcpParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_ucx_jucx_Bridge_createContextNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_ucx_jucx_Bridge
 * Method:    cleanupContextNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_Bridge_cleanupContextNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ucx_jucx_Bridge
 * Method:    createWorkerNative
 * Signature: (Lorg/ucx/jucx/ucp/UcpWorkerParams;J)J
 */
JNIEXPORT jlong JNICALL Java_org_ucx_jucx_Bridge_createWorkerNative
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_ucx_jucx_Bridge
 * Method:    releaseWorkerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_Bridge_releaseWorkerNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
