/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucp_UcpRemoteKey */

#ifndef _Included_org_ucx_jucx_ucp_UcpRemoteKey
#define _Included_org_ucx_jucx_ucp_UcpRemoteKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucp_UcpRemoteKey
 * Method:    rkeyDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpRemoteKey_rkeyDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
