/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucp_UcpEndpoint */

#ifndef _Included_org_ucx_jucx_ucp_UcpEndpoint
#define _Included_org_ucx_jucx_ucp_UcpEndpoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    createEndpointNative
 * Signature: (Lorg/ucx/jucx/ucp/UcpEndpointParams;J)J
 */
JNIEXPORT jlong JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_createEndpointNative
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    destroyEndpointNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_destroyEndpointNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    unpackRemoteKey
 * Signature: (JLjava/nio/ByteBuffer;)Lorg/ucx/jucx/ucp/UcpRemoteKey;
 */
JNIEXPORT jobject JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_unpackRemoteKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    putNonBlockingNative
 * Signature: (JLjava/nio/ByteBuffer;JJLorg/ucx/jucx/UcxCallback;)Lorg/ucx/jucx/UcxRequest;
 */
JNIEXPORT jobject JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_putNonBlockingNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject);

/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    getNonBlockingNative
 * Signature: (JJJLjava/nio/ByteBuffer;Lorg/ucx/jucx/UcxCallback;)Lorg/ucx/jucx/UcxRequest;
 */
JNIEXPORT jobject JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_getNonBlockingNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject, jobject);

/*
 * Class:     org_ucx_jucx_ucp_UcpEndpoint
 * Method:    sendTaggedNonBlockingNative
 * Signature: (JLjava/nio/ByteBuffer;JLorg/ucx/jucx/UcxCallback;)Lorg/ucx/jucx/UcxRequest;
 */
JNIEXPORT jobject JNICALL Java_org_ucx_jucx_ucp_UcpEndpoint_sendTaggedNonBlockingNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
