/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucp_UcpMemory */

#ifndef _Included_org_ucx_jucx_ucp_UcpMemory
#define _Included_org_ucx_jucx_ucp_UcpMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucp_UcpMemory
 * Method:    unmapMemoryNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpMemory_unmapMemoryNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_ucx_jucx_ucp_UcpMemory
 * Method:    getRkeyBufferNative
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_ucx_jucx_ucp_UcpMemory_getRkeyBufferNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_ucx_jucx_ucp_UcpMemory
 * Method:    releaseRkeyBufferNative
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpMemory_releaseRkeyBufferNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
