/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucp_UcpListener */

#ifndef _Included_org_ucx_jucx_ucp_UcpListener
#define _Included_org_ucx_jucx_ucp_UcpListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucp_UcpListener
 * Method:    createUcpListener
 * Signature: (Lorg/ucx/jucx/ucp/UcpListenerParams;J)J
 */
JNIEXPORT jlong JNICALL Java_org_ucx_jucx_ucp_UcpListener_createUcpListener
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_ucx_jucx_ucp_UcpListener
 * Method:    destroyUcpListenerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucp_UcpListener_destroyUcpListenerNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
