/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucs_UcsConstants */

#ifndef _Included_org_ucx_jucx_ucs_UcsConstants
#define _Included_org_ucx_jucx_ucs_UcsConstants
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ucx_jucx_ucs_UcsConstants
 * Method:    loadConstants
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ucx_jucx_ucs_UcsConstants_loadConstants
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
