/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ucx_jucx_ucs_UcsConstants_ThreadMode */

#ifndef _Included_org_ucx_jucx_ucs_UcsConstants_ThreadMode
#define _Included_org_ucx_jucx_ucs_UcsConstants_ThreadMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
