version: "3"

services:
  centos7-mofed5-cuda11:
    image: centos7-mofed5-cuda11:2
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 11.4.0
        OS_VERSION: 7
  centos7-mofed5.4-cuda11:
    image: centos7-mofed5.4-cuda11
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.4-1.0.3.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 11.2.0
        OS_VERSION: 7
  centos8-mofed5-cuda11:
    image: centos8-mofed5-cuda11:2
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel8.2
        CUDA_VERSION: 11.4.0
        OS_VERSION: 8
  ubuntu16.04-mofed5-cuda11:
    image: ubuntu16.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 16.04
        CUDA_VERSION: 11.2.0
  ubuntu18.04-mofed5-cuda11:
    image: ubuntu18.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 11.4.0
  ubuntu20.04-mofed5-cuda11:
    image: ubuntu20.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 20.04
        CUDA_VERSION: 11.4.0
