/**
 * Copyright (c) NVIDIA CORPORATION & AFFILIATES, 2025. ALL RIGHTS RESERVED.
 *
 * See file LICENSE for terms.
 */

#ifndef LIBPERF_DEVICE_H_
#define LIBPERF_DEVICE_H_

#define HAVE_LIBPERF_DEVICE HAVE_CUDA

#endif // LIBPERF_DEVICE_H_
