jobs:
  - job: distro_release
    condition: eq(stageDependencies.Check_Commit.Check.outputs['Commit.Launch'], 'Yes')
    displayName: distro
    variables:
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        POSTFIX: ucx-${{ replace(variables['Build.SourceBranch'], 'refs/tags/', '') }}
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        POSTFIX: ucx-test

    pool:
      name: MLNX
      demands:
        - harbor_registry -equals yes

    strategy:
      matrix:
        centos7_cuda10_1:
          build_container: centos7_cuda10_1
          artifact_name: $(POSTFIX)-centos-cuda10.1.tar.bz2
        centos7_cuda10_2:
          build_container: centos7_cuda10_2
          artifact_name: $(POSTFIX)-centos-cuda10.2.tar.bz2
        centos7_cuda11_0:
          build_container: centos7_cuda11_0
          artifact_name: $(POSTFIX)-centos-cuda11.0.tar.bz2
        centos7_cuda11_2:
          build_container: centos7_cuda11_2
          artifact_name: $(POSTFIX)-centos-cuda11.2.tar.bz2
        ubuntu16_cuda10_1:
          build_container: ubuntu16_cuda10_1
          artifact_name: $(POSTFIX)-ubuntu-cuda10.1.deb
        ubuntu16_cuda10_2:
          build_container: ubuntu16_cuda10_2
          artifact_name: $(POSTFIX)-ubuntu-cuda10.2.deb
        ubuntu16_cuda11_0:
          build_container: ubuntu16_cuda11_0
          artifact_name: $(POSTFIX)-ubuntu-cuda11.0.deb
        ubuntu16_cuda11_2:
          build_container: ubuntu16_cuda11_2
          artifact_name: $(POSTFIX)-ubuntu-cuda11.2.deb


    container: $[ variables['build_container'] ]

    steps:
      - checkout: self
        clean: true
        fetchDepth: 100
        path: "we/need/to/go/deeper"
        # ^ Avoid rpmbuild error: Dest dir longer than base dir is not supported

      - bash: |
          set -eE
          ./autogen.sh
          mkdir pkg-build
          cd pkg-build
          ../contrib/configure-release --with-cuda --with-java=no
        displayName: Configure

      - bash: |
          set -eE
          cd pkg-build
          ../contrib/buildrpm.sh -s -t -b
          cd rpm-dist/`uname -m`
          tar -cjf "../../../${AZ_ARTIFACT_NAME}" *.rpm
          cd ../../..
          tar -tjf "${AZ_ARTIFACT_NAME}"
        displayName: Build RPM package
        condition: and(succeeded(), contains(variables['artifact_name'], 'centos'))
        env:
          AZ_ARTIFACT_NAME: $(artifact_name)

      - bash: |
          set -eE
          cd pkg-build
          dpkg-buildpackage -us -uc
          find .. -name '*.deb'
          find .. -name '*.deb' -exec cp {} "../${AZ_ARTIFACT_NAME}" \;
          dpkg-deb -I "../${AZ_ARTIFACT_NAME}"
        displayName: Build DEB package
        condition: and(succeeded(), contains(variables['artifact_name'], 'ubuntu'))
        env:
          AZ_ARTIFACT_NAME: $(artifact_name)

      - task: GithubRelease@0
        condition: eq(variables['Build.Reason'], 'ResourceTrigger')
        displayName: Upload artifacts to draft release
        inputs:
          githubConnection: release
          repositoryName: openucx/ucx
          action: edit
          tag: $(Build.SourceBranchName)
          isDraft: true
          addChangeLog: false
          assetUploadMode: replace
          assets: "./$(artifact_name)"
