# Create an empty draft to avoid race condition in distro release

parameters:
  arch:
  container:  
  demands: []

jobs:
  - job: DraftRelease_${{ parameters.arch }}
    displayName: Draft release ${{ parameters.arch }}
    container: ${{ parameters.container }}    
    pool:
      name: MLNX
      demands: ${{ parameters.demands }}

    steps:
    - checkout: self
      clean: true
      fetchDepth: 100
      path: "we/need/to/go/deeper"
      retryCountOnTaskFailure: 5

    - bash: ./autogen.sh
      displayName: Setup autotools

    - bash: |
        set -eEx
        # gcc --version
        ./contrib/configure-release --with-java=no
        ./contrib/buildrpm.sh -s -t -b
      displayName: Build tarball

    - task: GithubRelease@0
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: Create/edit GitHub Draft Release
      inputs:
        githubConnection: release
        repositoryName: openucx/ucx
        action: edit
        tag: $(Build.SourceBranchName)
        isDraft: true
        addChangeLog: false
        releaseNotesSource: file
        releaseNotesFile: NEWS
        assetUploadMode: replace
        assets: |
          ./ucx-*.tar.gz
          ./rpm-dist/ucx-*.src.rpm
