version: "3"

services:
  centos7-mofed5.0-cuda10.1:
    image: centos7-mofed5.0-cuda10.1
    build:
      context: .
      dockerfile: centos7-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 10.1
  centos7-mofed5.0-cuda10.2:
    image: centos7-mofed5.0-cuda10.2
    build:
      context: .
      dockerfile: centos7-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 10.2
  centos7-mofed5.0-cuda11.0:
    image: centos7-mofed5.0-cuda11.0
    build:
      context: .
      dockerfile: centos7-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 11.0
  ubuntu16.04-mofed5.0-cuda10.1:
    image: ubuntu16.04-mofed5.0-cuda10.1
    build:
      context: .
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 16.04
        CUDA_VERSION: 10.1
  ubuntu16.04-mofed5.0-cuda10.2:
    image: ubuntu16.04-mofed5.0-cuda10.2
    build:
      context: .
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 16.04
        CUDA_VERSION: 10.2
  ubuntu18.04-mofed5.0-cuda10.1:
    image: ubuntu18.04-mofed5.0-cuda10.1
    build:
      context: .
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 10.1
  ubuntu18.04-mofed5.0-cuda10.2:
    image: ubuntu18.04-mofed5.0-cuda10.2
    build:
      context: .
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 10.2
  ubuntu18.04-mofed5.0-cuda11.0:
    image: ubuntu18.04-mofed5.0-cuda11.0
    build:
      context: .
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 11.0

