var searchData=
[
  ['ucp_20api_0',['Unified Communication Protocol (UCP) API',['../group___u_c_p___a_p_i.html',1,'']]],
  ['ucp_20application_20context_1',['UCP Application Context',['../group___u_c_p___c_o_n_t_e_x_t.html',1,'']]],
  ['ucp_20communication_20routines_2',['UCP Communication routines',['../group___u_c_p___c_o_m_m.html',1,'']]],
  ['ucp_20configuration_3',['UCP Configuration',['../group___u_c_p___c_o_n_f_i_g.html',1,'']]],
  ['ucp_20data_20type_20routines_4',['UCP Data type routines',['../group___u_c_p___d_a_t_a_t_y_p_e.html',1,'']]],
  ['ucp_20endpoint_5',['UCP Endpoint',['../group___u_c_p___e_n_d_p_o_i_n_t.html',1,'']]],
  ['ucp_20memory_20routines_6',['UCP Memory routines',['../group___u_c_p___m_e_m.html',1,'']]],
  ['ucp_20wake_20up_20routines_7',['UCP Wake-up routines',['../group___u_c_p___w_a_k_e_u_p.html',1,'']]],
  ['ucp_20worker_8',['UCP Worker',['../group___u_c_p___w_o_r_k_e_r.html',1,'']]],
  ['ucs_20api_9',['Unified Communication Services (UCS) API',['../group___u_c_s___a_p_i.html',1,'']]],
  ['ucs_20communication_20resource_10',['UCS Communication Resource',['../group___u_c_s___r_e_s_o_u_r_c_e.html',1,'']]],
  ['uct_20active_20messages_11',['UCT Active messages',['../group___u_c_t___a_m.html',1,'']]],
  ['uct_20api_12',['Unified Communication Transport (UCT) API',['../group___u_c_t___a_p_i.html',1,'']]],
  ['uct_20atomic_20operations_13',['UCT Atomic operations',['../group___u_c_t___a_m_o.html',1,'']]],
  ['uct_20client_20server_20operations_14',['UCT client-server operations',['../group___u_c_t___c_l_i_e_n_t___s_e_r_v_e_r.html',1,'']]],
  ['uct_20communication_20context_15',['UCT Communication Context',['../group___u_c_t___c_o_n_t_e_x_t.html',1,'']]],
  ['uct_20communication_20resource_16',['UCT Communication Resource',['../group___u_c_t___r_e_s_o_u_r_c_e.html',1,'']]],
  ['uct_20interface_20for_20asynchronous_20event_20capabilities_17',['UCT interface for asynchronous event capabilities',['../group___u_c_t___r_e_s_o_u_r_c_e___i_f_a_c_e___e_v_e_n_t___c_a_p.html',1,'']]],
  ['uct_20interface_20operations_20and_20capabilities_18',['UCT interface operations and capabilities',['../group___u_c_t___r_e_s_o_u_r_c_e___i_f_a_c_e___c_a_p.html',1,'']]],
  ['uct_20memory_20domain_19',['UCT Memory Domain',['../group___u_c_t___m_d.html',1,'']]],
  ['uct_20remote_20memory_20access_20operations_20',['UCT Remote memory access operations',['../group___u_c_t___r_m_a.html',1,'']]],
  ['uct_20tag_20matching_20operations_21',['UCT Tag matching operations',['../group___u_c_t___t_a_g.html',1,'']]],
  ['unified_20communication_20protocol_20ucp_20api_22',['Unified Communication Protocol (UCP) API',['../group___u_c_p___a_p_i.html',1,'']]],
  ['unified_20communication_20services_20ucs_20api_23',['Unified Communication Services (UCS) API',['../group___u_c_s___a_p_i.html',1,'']]],
  ['unified_20communication_20transport_20uct_20api_24',['Unified Communication Transport (UCT) API',['../group___u_c_t___a_p_i.html',1,'']]],
  ['up_20routines_25',['UCP Wake-up routines',['../group___u_c_p___w_a_k_e_u_p.html',1,'']]]
];
