parameters:
  - name: demands
    type: string
    default: "ucx_iodemo -equals yes"
  - name: initial_delay
    type: number
    default: 20
  - name: cycles
    type: number
    default: 100
  - name: downtime
    type: number
    default: 5
  - name: uptime
    type: number
    default: 40
  - name: tests
    type: object
    default:
      tag:
        args: ""
        duration: 480
      active:
        args: "-q -A"
        duration: 480

jobs:
  - job: io_build
    displayName: Build io_demo

    pool:
      name: MLNX
      demands: ${{ parameters.demands }}

    steps:
      # address permissions issue when some files created as read-only
      - bash: chmod u+rwx ./ -R

      - checkout: self
        clean: true
        fetchDepth: 100
        displayName: Checkout
      - bash: |
          set -eEx
          ./autogen.sh
          ./contrib/configure-release --prefix=$(Build.Repository.LocalPath)/install
          make -j`nproc`
          make install
        displayName: Build
        name: build
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.Repository.LocalPath)'
          contents: |
            buildlib/az-helpers.sh
            buildlib/az-network-corrupter.sh
            buildlib/io_demo/iodemo_analyzer.py
            install/**
            test/apps/iodemo/run_io_demo.sh
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop_$(Build.BuildId)

  - job: test
    dependsOn: io_build

    pool:
      name: MLNX
      demands: ${{ parameters.demands }}

    strategy:
      matrix:
        ${{ each test in parameters.tests }}:
          ${{ test.Key }}:
            test_name: ${{ test.Key }}
            test_args: ${{ test.Value.args }}
            test_time: ${{ test.Value.duration }}
      maxParallel: 1

    variables:
      workspace: drop_$(Build.BuildId)
      io_demo_exe: drop_$(Build.BuildId)/install/bin/io_demo
      initial_delay: ${{ parameters.initial_delay }}
      cycles: ${{ parameters.cycles }}
      downtime: ${{ parameters.downtime }}
      uptime: ${{ parameters.uptime }}


    displayName: "io_demo: "
    steps:
      - checkout: none
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          artifactName: drop_$(Build.BuildId)
          downloadPath: $(System.DefaultWorkingDirectory)
      - bash: chmod u+rwx $(workspace) -R
      - template: az-stage-io-demo.yaml
        parameters:
          name: $(test_name)
          iodemo_args: $(test_args)
          duration: $(test_time)
