/**
* Copyright (C) UT-Battelle, LLC. 2014. ALL RIGHTS RESERVED.
* $COPYRIGHT$
* $HEADER$
*/

#ifndef UCT_UGNI_CONTEXT_H
#define UCT_UGNI_CONTEXT_H

#include "ugni_device.h"

typedef struct uct_ugni_context {
    uint8_t             ptag;               /**< Protection tag */
    uint32_t            cookie;             /**< Unique identifier generated by the PMI system */
    gni_cdm_handle_t    cdm_handle;         /**< Ugni communication domain */
    int                 pmi_num_of_ranks;   /**< Number of ranks started by PMI */
    int                 pmi_rank_id;        /**< rank id assigned by PMI */
    int                 num_devices;        /**< Number of devices */
    uct_ugni_device_t   *devices;           /**< Array of devices */
    pid_t               id;                 /**< Unique identifier of the process */
    bool                activated;          /**< Context status */
} uct_ugni_context_t;

/*
 * Helper function to list UGNI resources
 */
ucs_status_t uct_ugni_query_resources(uct_context_h context,
                                    uct_resource_desc_t **resources_p,
                                    unsigned *num_resources_p);

uct_ugni_device_t * uct_ugni_device_by_name(uct_ugni_context_t * ugni_ctx,
        const char *dev_name);
#endif
