jobs:
  - job: io_build
    displayName: Build io_demo
    workspace:
      clean: all

    pool:
      name: MLNX
      demands: ucx_docker -equals yes
    container: centos7

    steps:
      # address permissions issue when some files created as read-only
      - bash: chmod u+rwx ./ -R

      - checkout: self
        clean: true
        fetchDepth: 100
        displayName: Checkout
        retryCountOnTaskFailure: 5
      - bash: |
          set -eEx
          ./autogen.sh
          ./contrib/configure-devel --prefix=$(Build.Repository.LocalPath)/install --without-go --without-java --disable-gtest --disable-examples
          make -j`nproc`
          make install
        displayName: Build
        name: build
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.Repository.LocalPath)'
          contents: |
            buildlib/az-helpers.sh
            buildlib/az-network-corrupter.sh
            install/**
            test/apps/iodemo/run_io_demo.sh
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop_$(Build.BuildId)

  - template: jobs-io-demo.yaml
    parameters:
      demands: "ucx_iodemo -equals yes"
      name: "with_interference"
      tests:
        "tag match on CX6/RC":
          interface: $(roce_iface_cx6)
          tls: "rc_x"
          test_name: tag_cx6_rc
        "active messages on CX6/RC":
          args: "-A"
          interface: $(roce_iface_cx6)
          tls: "rc_x"
          test_name: am_cx6_rc
        "tag match on CX6/DC":
          interface: $(roce_iface_cx6)
          tls: "dc_x"
          test_name: tag_cx6_dc
        "active messages on CX6/DC with data validation":
          args: "-A -q"
          interface: $(roce_iface_cx6)
          tls: "dc_x"
          test_name: am_validate_cx6_dc
        "tag match on CX6/DC with auto ECE":
          args: ""
          interface: $(roce_iface_cx6)
          tls: "dc_x"
          ece: "auto"
          test_name: tag_cx6_dc_auto_ece

  - template: jobs-io-demo.yaml
    parameters:
      demands: "ucx_iodemo_without_interference -equals yes"
      name: "without_interference"
      duration: 120
      interference: 'No'
      tests:
        "active messages on CX6/DC with user memh":
          args: "-A -z"
          interface: $(roce_iface_cx6)
          tls: "dc_x"
          test_name: am_umemh_cx6_dc
        "different UCX_IB_NUM_PATH":
          args: "-A"
          interface: $(roce_iface_cx6)
          tls: "rc_x"
          test_name: am_cx6_num_path
          extra_run_args: "--env client UCX_IB_NUM_PATHS=1 --env server UCX_IB_NUM_PATHS=2"
